**Name:** Muhammad Umer

**Email** umerhayat282@gmail.com

**Date** October 07, 2025

____

**Array Creation**

- Create a 1D NumPy array with elements ranging from 0 to 9.
- Create a 3x3 NumPy array filled with the value 7.

In [2]:
import numpy as np

In [4]:
a = np.arange(10)
a.ndim

1

In [8]:
ar = np.full((3,3), 7)
ar

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

**Array Operations**

- Create two 2D arrays of shape (3, 3) and perform element-wise addition and
multiplication.
- Create a 4x4 array of random integers between 10 and 50. Find the maximum and
minimum values in the array.

In [16]:
a_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a_2 = np.array([[3,2,1],[6,5,4],[9,8,7]])

ad = a_1 + a_2 
print(ad)

mul = a_1 * a_2 
print(mul)


[[ 4  4  4]
 [10 10 10]
 [16 16 16]]
[[ 3  4  3]
 [24 25 24]
 [63 64 63]]


In [18]:
import random

In [25]:
arr = np.random.randint(10, 51, size=(4, 4))
print(arr)


print(arr.max())

print(arr.min())

[[15 19 18 28]
 [11 31 15 25]
 [41 18 32 12]
 [34 24 41 22]]
41
11


**Indexing and Slicing**

- Create a 5x5 array of sequential numbers starting from 1. Extract the middle 3x3 sub-
array.
- Given a 2D array of shape (4, 4), set all elements in the first row to 0.

In [28]:
arr = np.arange(1,26).reshape(5,5)
print(arr)
middle_array = arr[1:4,1:4]
print(middle_array)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [32]:
arr = np.random.randint(1,10, size=(4,4))
print(f"Original Array:\n {arr}")

arr[0,:] = 0

print(f"Modified Array:\n {arr}")

Original Array:
 [[4 9 7 6]
 [9 3 3 4]
 [4 8 3 9]
 [1 5 4 6]]
Modified Array:
 [[0 0 0 0]
 [9 3 3 4]
 [4 8 3 9]
 [1 5 4 6]]


**Mathematical Operations**

- Compute the mean, median, and standard deviation of a randomly generated array of
1000 elements.
- Perform a dot product of two 1D arrays of length 4.

In [39]:
arr = np.arange(np.random.randint(1000))
print(arr.mean())
print(np.median(arr))
print(arr.std()) 

374.0
374.0
216.21748310439654


In [49]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])


dot_product = np.dot(arr1, arr2)

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Dot Product:", dot_product)

Array 1: [1 2 3 4]
Array 2: [5 6 7 8]
Dot Product: 70


**Broadcasting**

- Create a 5x5 array of zeros and add a 1D array of shape (5,) to each row of the 2D array
using broadcasting.
- Create a 3x3 array and subtract a scalar value from it.

In [18]:
arr = np.zeros((5,5))
arr2 = np.array([1, 2, 3, 4, 5])

result = arr + arr2
print(f"Array one of Zeros:\n {arr}")
print("--"*15)
print(f"1D array of shape 5:\n {arr2}")
print("--"*15)
print(result)


Array one of Zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
------------------------------
1D array of shape 5:
 [1 2 3 4 5]
------------------------------
[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


In [24]:
arr = np.random.randint(1,9, size=(3,3))
print(f"3x3 Array of random Value:\n {arr}")

scaler_value = 2

result = arr - scaler_value
print(f"Result after Subtraction:\n {result}")

3x3 Array of random Value:
 [[6 7 5]
 [2 6 4]
 [1 7 6]]
Result after Subtraction:
 [[ 4  5  3]
 [ 0  4  2]
 [-1  5  4]]


**Aggregations**

- Calculate the sum of all elements in a 6x6 array with random values between 1 and 10.
- Find the index of the maximum value in a 1D array of 50 random values.

In [30]:
arr = np.random.randint(1,10, size=(6,6))
print(f"6x6 Array of Random value from 1 to 10:\n {arr}")
print(f"Shape:\n {arr.shape}")
print(f"Dimension:\n {arr.ndim}")


print(f"The sum of an array:\n {sum(arr)}")

6x6 Array of Random value from 1 to 10:
 [[8 2 5 3 7 6]
 [1 6 8 3 7 7]
 [3 2 3 7 5 6]
 [3 5 1 2 2 8]
 [9 5 1 1 7 8]
 [7 2 8 9 2 9]]
Shape:
 (6, 6)
Dimension:
 2
The sum of an array:
 [31 22 26 25 30 44]


In [37]:
arr = np.random.rand(50)
print(f"Random Array: \n{arr}")

index = np.argmax(arr)
print(f"Maximum Index: \n {index}")

Random Array: 
[0.35932294 0.48434832 0.32364167 0.26708742 0.57966331 0.98359675
 0.57497292 0.31334428 0.99408765 0.40445058 0.72660265 0.11439685
 0.36200973 0.19560402 0.27772473 0.40084852 0.49086683 0.97595054
 0.27370268 0.94655475 0.22753455 0.07916287 0.63418861 0.09589776
 0.96974552 0.64448457 0.63509868 0.34766884 0.48339645 0.54293256
 0.89865173 0.81890441 0.23039131 0.166448   0.71495989 0.60419249
 0.89008816 0.35815129 0.42774764 0.74308531 0.62828445 0.04084428
 0.49272698 0.25710882 0.52886385 0.20042613 0.49970174 0.29900808
 0.40297598 0.01320176]
Maximum Index: 
 8


**Reshaping and Flattening**

- Reshape a 1D array of 12 elements into a 3x4 array.
- Flatten a 4x4 array into a 1D array.

In [43]:
arr = np.random.rand(12)
print(f"1D Array of 12 elements: \n {arr}")
arr2 = arr.reshape(3,4)
print(f"After Reshaping: \n {arr2}")
print(f"Shape: \n {arr2.shape}")

1D Array of 12 elements: 
 [0.15840722 0.03365622 0.43382316 0.35738577 0.74769281 0.43245408
 0.27968043 0.68733469 0.43403947 0.25331816 0.20260076 0.77675945]
After Reshaping: 
 [[0.15840722 0.03365622 0.43382316 0.35738577]
 [0.74769281 0.43245408 0.27968043 0.68733469]
 [0.43403947 0.25331816 0.20260076 0.77675945]]
Shape: 
 (3, 4)


In [49]:
arr = np.random.randint(1,20, size=(4,4))
print(f"4x4 Array: \n {arr}")
print(f"Shape of 4x4 Array: \n {arr.shape}")
print(f"Dimension of 4x4 Array: \n {arr.ndim}")
print("--"*15)

arr2 = arr.flatten()
print(f"4x4 Array after flatten: \n {arr2}")
print(f"Shape of 4x4 Array after flatten: \n {arr2.shape}")
print(f"Dimension of 4x4 Array after flatten: \n {arr2.ndim}")


4x4 Array: 
 [[11  4  9 11]
 [12 12  4  2]
 [17 17 17 19]
 [11 11 14  5]]
Shape of 4x4 Array: 
 (4, 4)
Dimension of 4x4 Array: 
 2
------------------------------
4x4 Array after flatten: 
 [11  4  9 11 12 12  4  2 17 17 17 19 11 11 14  5]
Shape of 4x4 Array after flatten: 
 (16,)
Dimension of 4x4 Array after flatten: 
 1


**Linear Algebra**

- Solve a system of linear equations represented by a 2x2 matrix and a 2x1 vector.
- Compute the inverse of a 3x3 matrix (if it is invertible).

In [53]:
A = np.array([[2, 1],
              [1, 3]])

b = np.array([8, 13])
print(f"Shape of Matrix A: \n {A.shape}")
print(f"Shape of Vector b: \n {b.shape}")

x = np.linalg.solve(A, b)

print("Solution vector x:", x)


Shape of Matrix A: 
 (2, 2)
Shape of Vector b: 
 (2,)
Solution vector x: [2.2 3.6]


In [55]:
M = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

deter = np.linalg.det(M)

if deter != 0:
    print(f"Inverse of the Matrix:\n {np.linalg.inv(M)}")
else:
    print(f"Matrix is not invertible (determinant = 0)")

Inverse of the Matrix:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]



**Statistical Analysis**

- Create a 100x100 array of random numbers and calculate the correlation coefficient
matrix.
- Compute the cumulative sum of a 1D array of 20 elements.

In [63]:
arr = np.random.randint(1,50, size=(100,100))
print(f"100x100 Array of Random Numbers: \n {arr}")
print("--"*20)
print(f"Shape of 100x100 Array of Random Numbers: \n {arr.shape}")
print("--"*20)

corr = np.corrcoef(arr)
print(f"Correlation Coeficient: \n {arr}")

100x100 Array of Random Numbers: 
 [[20 20 16 ...  5 30 39]
 [42  5 24 ... 22 48 22]
 [24  9 27 ...  3  8 10]
 ...
 [44  5 35 ... 25  9  8]
 [14  8 12 ... 24 41 16]
 [ 8 34 48 ... 32  3 43]]
----------------------------------------
Shape of 100x100 Array of Random Numbers: 
 (100, 100)
----------------------------------------
Correlation Coeficient: 
 [[20 20 16 ...  5 30 39]
 [42  5 24 ... 22 48 22]
 [24  9 27 ...  3  8 10]
 ...
 [44  5 35 ... 25  9  8]
 [14  8 12 ... 24 41 16]
 [ 8 34 48 ... 32  3 43]]


In [68]:
arr = np.arange(20)
print(f"1D Array of 20 Different Element: \n {arr} \n Shape:\n {arr.shape} \n Dimension: \n {arr.ndim}")

arr2 = np.cumsum(arr)
print(f"Cummulative Sum: \n {arr2}")

1D Array of 20 Different Element: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 
 Shape:
 (20,) 
 Dimension: 
 1
Cummulative Sum: 
 [  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190]


**Advanced Indexing**

- Create a 4x4 matrix and use boolean indexing to set all elements greater than 5 to -1.
- Generate a 2D array of shape (5, 5) and use advanced indexing to extract specific rows
and columns based on conditions.

In [70]:
arr = np.random.randint(1, 10, size=(4, 4))
print("Original array:\n", arr)

arr[arr > 5] = -1
print("\nModified array:\n", arr)




Original array:
 [[8 1 9 1]
 [6 9 6 2]
 [7 4 1 6]
 [9 4 7 9]]

Modified array:
 [[-1  1 -1  1]
 [-1 -1 -1  2]
 [-1  4  1 -1]
 [-1  4 -1 -1]]


In [72]:
data = np.arange(25).reshape(5, 5)
print("Original 5x5 array:\n", data)


# Example: extract rows where the first column > 10
rows = data[data[:, 0] > 10]

# Example: extract specific columns (say 1 and 3)
cols = data[:, [1, 3]]


print("\nRows where first column > 10:\n", rows)
print("\nColumns 1 and 3:\n", cols)

Original 5x5 array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Rows where first column > 10:
 [[15 16 17 18 19]
 [20 21 22 23 24]]

Columns 1 and 3:
 [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]
 [21 23]]


___