**Name:** Muhammad Umer

**Email** umerhayat282@gmail.com

**Date** October 09, 2025

____

##   NumPy Tasks:


**1. Create a NumPy Array:** Create a 2D NumPy array with the shape (3, 4), filled with
random integers between 1 and 100.

In [58]:
import numpy as np



In [59]:
array = np.random.randint(1,100, size=(3,4))
print(array)
array.shape

[[93 99 45 71]
 [58  6 69 71]
 [11  2 57 72]]


(3, 4)

**2. Array Operations:** Perform element-wise addition and subtraction between two
NumPy arrays of shape (3, 4), where the first array contains even numbers and the
second contains odd numbers.

In [60]:
array1 = np.random.choice(np.arange(0,100,2), size=(3,4))
array2 = np.random.choice(np.arange(1,100,2), size=(3,4))
print(array1)
print("--"*10)
print(array2)
addition = array1 + array2
subtraction = array2 - array1
print("=="*10)
print(addition)
print("--"*10)
print(subtraction)

[[42 16 82 56]
 [94 62 80 56]
 [96 14 46 16]]
--------------------
[[67 51 21 75]
 [ 1 95 15  7]
 [83 51 73 45]]
[[109  67 103 131]
 [ 95 157  95  63]
 [179  65 119  61]]
--------------------
[[ 25  35 -61  19]
 [-93  33 -65 -49]
 [-13  37  27  29]]



**3. Find Maximum and Minimum:** Find the maximum and minimum values in a 1D
NumPy array of 20 random integers between 1 and 50.

In [61]:
array = np.random.randint(1,50, size=(20))
print(f"Array: \n {array}")
print(f"Dimensions: {array.ndim}")
print(f"Maximum Value: {array.max()}")
print(f"Minimum Value: {array.min()}")



Array: 
 [25  6 31  4 17 49  8 35 11 27 15 22 20  2 11 42  7  5 12 26]
Dimensions: 1
Maximum Value: 49
Minimum Value: 2


**4. Matrix Multiplication:** Create two 3x3 NumPy arrays and multiply them using the
dot product.

In [62]:
array1 = np.random.randint(1,10, size=(3,3))
array2 = np.random.randint(1,10, size=(3,3))
print(array1)
print("--"*10)
print(array2)
print("--"*10)
dot_product = np.dot(array1, array2)
print(dot_product)

[[2 9 1]
 [9 4 8]
 [4 1 4]]
--------------------
[[3 3 6]
 [9 7 5]
 [2 7 8]]
--------------------
[[ 89  76  65]
 [ 79 111 138]
 [ 29  47  61]]



**5. Transpose of a Matrix:** Create a 3x3 matrix and compute its transpose using NumPy.

In [63]:
matrix = np.random.randint(1,10, size=(3,3))
print(matrix)
transpose = np.transpose(matrix)
print("--"*10)
print(transpose)

[[2 4 6]
 [4 6 3]
 [8 3 1]]
--------------------
[[2 4 8]
 [4 6 3]
 [6 3 1]]


**6. Array Reshaping:** Take a 1D NumPy array of length 12 and reshape it into a 3x4 2D
array.

In [64]:
array = np.random.randint(1,100, size=(12))
reshaped_array = array.reshape(3,4)
print(array)
print("--"*10)
print(reshaped_array)

[45 32 42 52 40 68 62  8 15 40 23 14]
--------------------
[[45 32 42 52]
 [40 68 62  8]
 [15 40 23 14]]


**7. Boolean Indexing:** Given a 1D NumPy array of integers, filter and return only the
elements greater than 25.

In [65]:
array = np.random.randint(1,100, size=(20))
filtered_array = array[array > 25]
print(f"Original Array: \n {array}")
print("--"*10)
print(f"Filtered Array: \n {filtered_array}")

Original Array: 
 [28 85 45 13 37 37 42 87 34 45 94 40 63 96 43 46 44 94  6 28]
--------------------
Filtered Array: 
 [28 85 45 37 37 42 87 34 45 94 40 63 96 43 46 44 94 28]


**8. Array Broadcasting:** Use broadcasting to add a 1D NumPy array of shape (1, 4) to a
2D NumPy array of shape (3, 4).

In [66]:
array1 = np.random.randint(1,10, size=(1,4))
array2 = np.random.randint(1,10, size=(3,4))
print(array1)
print("--"*10)
print(array2)
print("--"*10)
addition = array1 + array2
print(addition)

[[8 9 7 5]]
--------------------
[[9 2 9 1]
 [8 2 2 2]
 [6 8 7 3]]
--------------------
[[17 11 16  6]
 [16 11  9  7]
 [14 17 14  8]]


**9. Standard Deviation:** Compute the standard deviation of a 1D NumPy array
containing 50 random values between 0 and 100.

In [67]:
array = np.random.randint(0,100, size=(50))
print(f"Array: \n {array}")
std_dev = np.std(array)
print(f"Standard Deviation: {std_dev}")

Array: 
 [31 68 33 71 10 38 96 57 79 57 98 58 53 56 80 28 39 99 55 99 91 47 48 16
 41 70  7 73 67 99 93 14 44 46 82  8 89 48 20 83 55 92 87 14 62 33 39 74
 52 24]
Standard Deviation: 27.21559111979749


___

##  Pandas DataFrame Tasks:

In [68]:
import pandas as pd


**1. Create a DataFrame:** Create a Pandas DataFrame with columns Name, Age,
Department and fill it with data for 5 employees.

In [69]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [25, 30, 35, 40, 45],
    "Department": ["HR", "Finance", "IT", "Marketing", "Sales"]
}

df = pd.DataFrame(data)
df

Name  Age Department
0    Alice   25         HR
1      Bob   30    Finance
2  Charlie   35         IT
3    David   40  Marketing
4      Eva   45      Sales

**2. Filter Rows:** From a DataFrame containing employee data, filter and return all
employees who are older than 30 years.

In [70]:
older_than_30 = df[df['Age'] > 30]
older_than_30

Name  Age Department
2  Charlie   35         IT
3    David   40  Marketing
4      Eva   45      Sales


**3. Update Column:** Update the Age column of a DataFrame to add 2 years to each
employee’s age.

In [71]:
df['Age'] = df['Age'] + 2
df

Name  Age Department
0    Alice   27         HR
1      Bob   32    Finance
2  Charlie   37         IT
3    David   42  Marketing
4      Eva   47      Sales



**4. Drop Columns:** Remove the Department column from the DataFrame of employees.

In [73]:
df.drop('Department', axis=1)

Name  Age
0    Alice   27
1      Bob   32
2  Charlie   37
3    David   42
4      Eva   47


**5. Group By and Count:** Given a DataFrame with employee data, group by
Department and count the number of employees in each department.

In [75]:
df.groupby('Department')["Name"].count()

Department
Finance      1
HR           1
IT           1
Marketing    1
Sales        1
Name: Name, dtype: int64


**6. Merge DataFrames:** Merge two DataFrames, one containing employee data and the
other containing salary data, based on a common ID column.

In [78]:
employee_data = {
    "ID": [1, 2, 3, 4, 5],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [25, 30, 35, 40, 45]
}

salary_data = {
    "ID": [1, 2, 3, 4, 5],
    "Salary": [50000, 60000, 70000, 80000, 90000]
}

employee_df = pd.DataFrame(employee_data)
salary_df = pd.DataFrame(salary_data)

In [79]:
print(employee_df)
print(salary_df)

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40
4   5      Eva   45
   ID  Salary
0   1   50000
1   2   60000
2   3   70000
3   4   80000
4   5   90000


In [81]:
merged_df = pd.merge(employee_df, salary_df, on="ID")
merged_df


ID     Name  Age  Salary
0   1    Alice   25   50000
1   2      Bob   30   60000
2   3  Charlie   35   70000
3   4    David   40   80000
4   5      Eva   45   90000

___